export default function SuggestionChips({ onSelect }) {
  const suggestions = [
    { label: "🔍 Analyze BONK", query: "Analyze BONK DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263" },
    { label: "⚖️ Compare BONK vs JUP", query: "Compare the risk profiles of DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263 and JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN" },
    { label: "🛡️ Is WIF safe?", query: "What is the rug probability for WIF right now?" },
    { label: "🚨 Latest Alerts", query: "Show me the latest security alerts generated by the agents" }
  ]

  return (
    <div className="flex flex-wrap gap-2 mt-4 justify-center md:justify-start">
      {suggestions.map((s, i) => (
        <button
          key={i}
          onClick={() => onSelect(s.query)}
          className="px-3 py-1.5 rounded-full border border-[#333333] bg-[#111111] text-slate-300 text-xs hover:bg-white hover:text-black hover:border-white transition-all font-medium whitespace-nowrap"
        >
          {s.label}
        </button>
      ))}
    </div>
  )
}
